### PR TITLE
Add LICENSE file

### PR DESCRIPTION
**Pull request by ablavatski**
Add license file for improved usability

### CODE REVIEW

**Comment by ablavatski** [comment]
@alexTitakoff gentle ping!

**Comment by alexTitakoff** [comment]
Sorry I didn't see it!
I haven't been working on the project for a long time (

**Comment by alexTitakoff** [comment]
I added your file. Thanks!

**Comment by alexTitakoff** [comment]
if anything, please contact alex.titakoff@yandex.ru 
: ]
I don't follow github very much, unfortunately

**Pull request closed without merging**
